version: '3.8'

services:
  comfyui:
    build: .
    image: comfyui:latest
    container_name: comfyui_container
    ports:
      - "8188:8188"
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./models:/app/models
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]