services:
  comfyui:
    build: .
    image: comfyui:latest
    container_name: comfyui_container
    ports:
      - "8188:8188"
    volumes:
      - ./ComfyUI:/app/ComfyUI
      - ./ComfyUI-Manager:/app/ComfyUI/custom_nodes/ComfyUI-Manager
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]